### ISSUE TITLE
invalid resources

### ISSUE THREAD

**Issue by jakoch** [fifengine/fifengine-atlas-creator#2]
some pngs are html pages... o.O 
https://github.com/fifengine/fifengine-atlas-creator/tree/master/src/resources

**Comment by LinuxDonald** [comment]
added save icon into the gui: https://github.com/fifengine/fifengine-atlas-creator/commit/a239d9d0df192f51dc4bb4aa6e611ecc81ddaf35

i will ask janexx for create an add and remove icon then i will fix the other icons :)
