### ISSUE TITLE
Port from qt4 to qt5

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fifengine-atlas-creator#7]
Port from qt4 to qt5

**Comment by jakoch** [comment]
Yes, needs porting, see https://travis-ci.org/fifengine/fifengine-atlas-creator/jobs/185223682#L473

**Comment by LinuxDonald** [comment]
Thank you alot for this @jakoch :+1:  :)

**Comment by LinuxDonald** [comment]
it have broken linux build:

> [linuxdonald@linuxdonald-pc src]$ make
> g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -D_REENTRANT -fPIC -DNOMINMAX -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -Ifreeglut/include -isystem /usr/include/qt -isystem /usr/include/qt/QtOpenGL -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o glwidget.o glwidget.cpp
> glwidget.cpp: In Elementfunktion »virtual void GLWidget::paintGL()«:
> glwidget.cpp:214:9: Warnung: verengende Umwandlung von »((GLWidget*)this)->GLWidget::texHeight« von »int« nach »float« in { } [-Wnarrowing]
>    0.0f, texHeight, 1.0f,
>          ^~~~~~~~~
> glwidget.cpp:215:3: Warnung: verengende Umwandlung von »((GLWidget*)this)->GLWidget::texWidth« von »int« nach »float« in { } [-Wnarrowing]
>    texWidth, texHeight, 1.0f,
>    ^~~~~~~~
> glwidget.cpp:215:13: Warnung: verengende Umwandlung von »((GLWidget*)this)->GLWidget::texHeight« von »int« nach »float« in { } [-Wnarrowing]
>    texWidth, texHeight, 1.0f,
>              ^~~~~~~~~
> glwidget.cpp:216:3: Warnung: verengende Umwandlung von »((GLWidget*)this)->GLWidget::texWidth« von »int« nach »float« in { } [-Wnarrowing]
>    texWidth, 0.0f, 1.0f,
>    ^~~~~~~~
> g++ -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro -o atlascreator main.o mainwindow.o glwidget.o objectcreator.o qrc_resources.o moc_mainwindow.o moc_glwidget.o moc_objectcreator.o   -L/home/linuxdonald/dev/fifengine-atlas-creator/src/freeglut/lib/ -lfreeglut -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
> /usr/bin/ld: cannot find -lfreeglut
> collect2: Fehler: ld gab 1 als Ende-Status zurück
> make: *** [Makefile:342: atlascreator] Fehler 1
> [linuxdonald@linuxdonald-pc src]$

**Comment by jakoch** [comment]
Some warnings, but then `cannot find -lfreeglut`.. the dependency freeglut isn't found on linux. 
We need to install the lib on travis and adjust the pro file to find/include it.
